# Copyright 2019 Vijay Kumar Banerjee (vijaykumar9597@gmail.com)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems
import rtems_waf.rtems_bsd as rtems_bsd

def configure(conf):
    rtems.check_lib_path(conf, lib = 'm')
    rtems.check_lib_path(conf, lib = 'lvgl', mandatory = False)
    rtems.check_lib_path(conf, lib = 'bsd', mandatory = False)

def build(bld):
    bld.recurse('hello')
    bld.recurse('gui')
