# Copyright 2013 Gedare Bloom (gedare@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems

def build(bld):
    bld.recurse('uboot_getenv')

