include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_SHARE)/make/directory.cfg

# Ticker Variations
SUBDIRS  = ticker
SUBDIRS += ticker_stackchk
SUBDIRS += ticker_trace
SUBDIRS += low_ticker
SUBDIRS += low_ticker1
SUBDIRS += low_ticker2 
