# Copyright 2013 Gedare Bloom (gedare@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems

def build(bld):
    bld.recurse('timer')
    bld.recurse('sem_server')
    bld.recurse('msg_server')
    bld.recurse('delay')
    bld.recurse('timer_server')
    bld.recurse('event_server')
    bld.recurse('timeout_event')
    bld.recurse('ratemon1')
    bld.recurse('ratemon2')
    if rtems.check_posix(bld):
        bld.recurse('ratemon_cond_server')
        bld.recurse('posix_cond_server')
        bld.recurse('posix_delay_nanosleep')
        bld.recurse('posix_delay_sleep')
        bld.recurse('posix_mutex_server')
        # This test requires POSIX and C++
        if bld.env['CXX'] is not None:
            bld.recurse('complex1')
