include $(RTEMS_MAKEFILE_PATH)/Makefile.inc
include $(RTEMS_CUSTOM)
include $(RTEMS_SHARE)/make/directory.cfg

SUBDIRS=hello_world_c 

# These use POSIX
SUBDIRS += portable_hello posix_hello_world both_hello
