# Copyright 2018 Joel Sherrill (joel@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)

    bld(features = 'c cprogram',
        target = 'psx_barrier_report.exe',
        source = ['barrier_attr_report.c','rtems_config.c'],
        lib = ['c'])

