# Copyright 2013 Chris Johns (chrisj@rtems.org)
# 
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

# Waf build script for an RTEMS Hello

import rtems_waf.rtems as rtems

version = "1.0.0"

def build(bld):
    rtems.build(bld)

    arch_bsp = bld.get_env()['RTEMS_ARCH_BSP']
    arch = bld.get_env()['RTEMS_ARCH']
    bsp = bld.get_env()['RTEMS_BSP']

    #
    # The include paths and defines.
    #
    bld.includes = ['.']
    bld.defines = ['PACKAGE_VERSION="' + version + '"']
    bld.cflags = ['-g', '-O']

    bld(features = 'c cprogram',
        target = 'hello',
        includes = bld.includes,
        defines = bld.defines,
        cflags = bld.cflags,
        source = ['test.c'])

