# Copyright 2013 Gedare Bloom (gedare@rtems.org)
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

import rtems_waf.rtems as rtems

def build(bld):
    if rtems.check_posix(bld):
        bld.recurse('psx_example_1')
        bld.recurse('psx_example_2')
        bld.recurse('psx_example_3')
        bld.recurse('psx_barrier_report')
        bld.recurse('psx_condvar_report')
        bld.recurse('psx_mqueue_report')
        bld.recurse('psx_mutex_report')
        bld.recurse('psx_pthread_report')
        bld.recurse('psx_rwlock_report')
        bld.recurse('psx_sched_report')
        bld.recurse('livermore')
