# Waf build script for an RTEMS classic_signal'
import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)

    bld(features = 'c cprogram',
        target = 'classic_signal',
        source = ['test.c'])
