# Waf build script for an RTEMS triple_period 
import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)

    bld(features = 'c cprogram',
        target = 'triple_period.exe',
        source = ['init.c', 'tasks.c'])
