# Copyright 2026 Joel Sherrill <joel@rtems.org>
#
# This file's license is 2-clause BSD as in this distribution's LICENSE.2 file.
#

# Waf build script for an RTEMS Hello
import rtems_waf.rtems as rtems

def build(bld):
    rtems.build(bld)

    bld(features = 'c cprogram',
        target = 'ticker_posix.exe',
        source = ['init.c', 'rtems_config.c'])
